### ISSUE TITLE
npm run build fails to minimize variadic.js

### ISSUE THREAD

**Issue by mradenovic** [variadicjs/variadicjs.github.io#11]
After `variadic.js` is imported, `npm run build` fails. 

**`npm run build` output**

```
> variadic-demo@0.1.0 build /home/mischa/dev/edu/nanodegree/mobile-web/variadicjs.github.io
> react-scripts build

Creating an optimized production build...
Failed to compile.


Failed to minify the code from this file:

        ./node_modules/variadic.js/lib/floatPrecise.js:1

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! variadic-demo@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the variadic-demo@0.1.0 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the variadic-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs variadic-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls variadic-demo
npm ERR! There is likely additional logging output above.

┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/mischa/.config │
└──────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mischa/.npm/_logs/2018-02-07T22_59_29_435Z-debug.log
```
**debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/heroku/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.5.0
3 info using node@v7.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle variadic-demo@0.1.0~prebuild: variadic-demo@0.1.0
6 silly lifecycle variadic-demo@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle variadic-demo@0.1.0~build: variadic-demo@0.1.0
8 verbose lifecycle variadic-demo@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle variadic-demo@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/mischa/dev/edu/nanodegree/mobile-web/variadicjs.github.io/node_modules/.bin:/home/mischa/dev/google_appengine:/usr/local/heroku/bin:/home/mischa/dev/google_appengine:/usr/local/heroku/bin:/home/mischa/dev/google_appengine:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle variadic-demo@0.1.0~build: CWD: /home/mischa/dev/edu/nanodegree/mobile-web/variadicjs.github.io
11 silly lifecycle variadic-demo@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
12 silly lifecycle variadic-demo@0.1.0~build: Returned: code: 1  signal: null
13 info lifecycle variadic-demo@0.1.0~build: Failed to exec build script
14 verbose stack Error: variadic-demo@0.1.0 build: `react-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid variadic-demo@0.1.0
16 verbose cwd /home/mischa/dev/edu/nanodegree/mobile-web/variadicjs.github.io
17 verbose Linux 4.4.0-112-generic
18 verbose argv "/usr/local/heroku/bin/node" "/usr/local/bin/npm" "run" "build"
19 verbose node v7.10.0
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 1
23 error variadic-demo@0.1.0 build: `react-scripts build`
23 error Exit status 1
24 error Failed at the variadic-demo@0.1.0 build script 'react-scripts build'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the variadic-demo package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     react-scripts build
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs variadic-demo
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls variadic-demo
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by jhowardjr** [comment]
👍 We'll work on getting a pre-compiled of the package working.

**Comment by amr08** [comment]
So after some research, this is due to the ES6 in the variadicJS file.  It has to run through webpack and babel-loader in order for it to be understood.  One fix to this is to run npm eject to customize webpack.  I started to head down this path, but then thought it would be better to open an issue in variadicjs so it can be more widely used.  Sounds like the folks over in variadic will get some practice running babel!

**Comment by jhowardjr** [comment]
variadic.js 0.0.20 should build now.

**Comment by mradenovic** [comment]
I can confirm that it builds with 0.0.20, so I'm gonna close this one for now.
